/**
 * Bitwarden employee roster, derived from a company-wide name list plus the
 * firstinitial+lastname@bitwarden.com email convention used elsewhere in this app.
 * These are NOT verified real email addresses — they're best-effort guesses so the
 * nominate-form's directory picker has real names to search against locally. Two
 * naming collisions (Alex/Addison Beck, Justin/Jason Miller) are disambiguated with
 * a two-letter first-name prefix instead of the usual single initial.
 *
 * Replace this with a real CSV export from Slack (see the Admin page's "Nominee
 * directory" import) as soon as one is available.
 */
export const EMPLOYEE_ROSTER_CSV = `
fullname,email,status,bots
Jess Velazco,jvelazco@bitwarden.com,Active,FALSE
Priya Mathew,pmathew@bitwarden.com,Active,FALSE
Fred Schillinger,fschillinger@bitwarden.com,Active,FALSE
Jon Maurer,jmaurer@bitwarden.com,Active,FALSE
Andrew Damiter,adamiter@bitwarden.com,Active,FALSE
Luc Schober,lschober@bitwarden.com,Active,FALSE
Mathew McCabe,mmccabe@bitwarden.com,Active,FALSE
Clayton Adams,cadams@bitwarden.com,Active,FALSE
Daniyel Danielyan,ddanielyan@bitwarden.com,Active,FALSE
Jordan Scott,jscott@bitwarden.com,Active,FALSE
Jared McCannon,jmccannon@bitwarden.com,Active,FALSE
Kelly Holmes,kholmes@bitwarden.com,Active,FALSE
Ryan Daugherty,rdaugherty@bitwarden.com,Active,FALSE
Shane Melton,smelton@bitwarden.com,Active,FALSE
Carley Diaz,cdiaz@bitwarden.com,Active,FALSE
Colton Hurst,churst@bitwarden.com,Active,FALSE
Troy Andrews,tandrews@bitwarden.com,Active,FALSE
Micah Edelblut,medelblut@bitwarden.com,Active,FALSE
Kenneth Simpson,ksimpson@bitwarden.com,Active,FALSE
Bart Falzarano,bfalzarano@bitwarden.com,Active,FALSE
Sean Jastrebski,sjastrebski@bitwarden.com,Active,FALSE
Kasey Babcock,kbabcock@bitwarden.com,Active,FALSE
Jessica Murillo,jmurillo@bitwarden.com,Active,FALSE
Jared Snider,jsnider@bitwarden.com,Active,FALSE
Sai Ferguson,sferguson@bitwarden.com,Active,FALSE
Brad Nagawiecki,bnagawiecki@bitwarden.com,Active,FALSE
Ethan Jobmann,ejobmann@bitwarden.com,Active,FALSE
Cetonia Bassey,cbassey@bitwarden.com,Active,FALSE
Kyle Spearrin,kspearrin@bitwarden.com,Active,FALSE
Jake Fink,jfink@bitwarden.com,Active,FALSE
Lynden Jones,ljones@bitwarden.com,Active,FALSE
Justin Baur,jbaur@bitwarden.com,Active,FALSE
Mike Stolyar,mstolyar@bitwarden.com,Active,FALSE
Jason Ng,jng@bitwarden.com,Active,FALSE
Alex Beck,abeck@bitwarden.com,Active,FALSE
Nicholas Nguyen,nnguyen@bitwarden.com,Active,FALSE
Patrick Beh-Forrest,pbehforrest@bitwarden.com,Active,FALSE
Kevin Flores,kflores@bitwarden.com,Active,FALSE
Gary Orenstein,gorenstein@bitwarden.com,Active,FALSE
Lima Leigh,lleigh@bitwarden.com,Active,FALSE
Trevor Fogle,tfogle@bitwarden.com,Active,FALSE
Joshua Todd,jtodd@bitwarden.com,Active,FALSE
Kevin Kost,kkost@bitwarden.com,Active,FALSE
Gabe Ovgard,govgard@bitwarden.com,Active,FALSE
Matt Bishop,mbishop@bitwarden.com,Active,FALSE
Anna Franklin,afranklin@bitwarden.com,Active,FALSE
Kendra Todd,ktodd@bitwarden.com,Active,FALSE
Ike Kottlowski,ikottlowski@bitwarden.com,Active,FALSE
Michael Gainey,mgainey@bitwarden.com,Active,FALSE
Adonish Krank,akrank@bitwarden.com,Active,FALSE
Matt Portune,mportune@bitwarden.com,Active,FALSE
Jonathan Prusik,jprusik@bitwarden.com,Active,FALSE
Brian Gentry,bgentry@bitwarden.com,Active,FALSE
Sukhleen Bolina,sbolina@bitwarden.com,Active,FALSE
Conner Turnbull,cturnbull@bitwarden.com,Active,FALSE
Evan Ledet,eledet@bitwarden.com,Active,FALSE
Baylor Randolph,brandolph@bitwarden.com,Active,FALSE
Austin Levy,alevy@bitwarden.com,Active,FALSE
Matthew Gibson,mgibson@bitwarden.com,Active,FALSE
Yashoda Walter,ywalter@bitwarden.com,Active,FALSE
Ryan Richetto,rrichetto@bitwarden.com,Active,FALSE
DaPriest Watson,dwatson@bitwarden.com,Active,FALSE
Marcus Casassa,mcasassa@bitwarden.com,Active,FALSE
Tresca Rightsell,trightsell@bitwarden.com,Active,FALSE
Ryan Luibrand,rluibrand@bitwarden.com,Active,FALSE
Kayla Gottlieb,kgottlieb@bitwarden.com,Active,FALSE
Devan Weed,dweed@bitwarden.com,Active,FALSE
Clay Sones,csones@bitwarden.com,Active,FALSE
Jake Christensen,jchristensen@bitwarden.com,Active,FALSE
Vince Grassia,vgrassia@bitwarden.com,Active,FALSE
AJ Mabry,amabry@bitwarden.com,Active,FALSE
Matt Cillis,mcillis@bitwarden.com,Active,FALSE
Everet Rummel,erummel@bitwarden.com,Active,FALSE
David Sakarthonsup,dsakarthonsup@bitwarden.com,Active,FALSE
Nina Zahri,nzahri@bitwarden.com,Active,FALSE
Ben Copping,bcopping@bitwarden.com,Active,FALSE
Stacy Grimes,sgrimes@bitwarden.com,Active,FALSE
Aaron Marshall,amarshall@bitwarden.com,Active,FALSE
Vincent Salucci,vsalucci@bitwarden.com,Active,FALSE
Octavio Cortes,ocortes@bitwarden.com,Active,FALSE
William Martin,wmartin@bitwarden.com,Active,FALSE
Todd Martin,tmartin@bitwarden.com,Active,FALSE
Phillip Coulombe,pcoulombe@bitwarden.com,Active,FALSE
Micaiah Martin,mmartin@bitwarden.com,Active,FALSE
Federico Maccaroni,fmaccaroni@bitwarden.com,Active,FALSE
Ben Jackson,bjackson@bitwarden.com,Active,FALSE
Thomas Rittson,trittson@bitwarden.com,Active,FALSE
Marika Gatasa,mgatasa@bitwarden.com,Active,FALSE
Timothy Chan,tchan@bitwarden.com,Active,FALSE
Jordan Cooks,jcooks@bitwarden.com,Active,FALSE
Mark Youssef,myoussef@bitwarden.com,Active,FALSE
Amanda Daly,adaly@bitwarden.com,Active,FALSE
Catherine Tung,ctung@bitwarden.com,Active,FALSE
Chinelo Ojialor,cojialor@bitwarden.com,Active,FALSE
Sami Kakar,skakar@bitwarden.com,Active,FALSE
Max Power,mpower@bitwarden.com,Active,FALSE
Daniel Smith,dsmith@bitwarden.com,Active,FALSE
Adam Bramley,abramley@bitwarden.com,Active,FALSE
Sugianto So,sso@bitwarden.com,Active,FALSE
Mughira Suliman,msuliman@bitwarden.com,Active,FALSE
Alex Zilber,azilber@bitwarden.com,Active,FALSE
Adedamola Aina,aaina@bitwarden.com,Active,FALSE
Cy Okeke,cokeke@bitwarden.com,Active,FALSE
Gbubemi Smith,gsmith@bitwarden.com,Active,FALSE
Tijani Yusuf,tyusuf@bitwarden.com,Active,FALSE
Michał Chęciński,mchecinski@bitwarden.com,Active,FALSE
André Bispo,abispo@bitwarden.com,Active,FALSE
Krystian Kan,kkan@bitwarden.com,Active,FALSE
Álison Fernandes,afernandes@bitwarden.com,Active,FALSE
Aleksandra Sikora,asikora@bitwarden.com,Active,FALSE
Saabirah Mohamed,smohamed@bitwarden.com,Active,FALSE
Carlos Gonçalves,cgoncalves@bitwarden.com,Active,FALSE
Kirsty Falconer Kruger,kkruger@bitwarden.com,Active,FALSE
André Rosado,arosado@bitwarden.com,Active,FALSE
Rui Tome,rtome@bitwarden.com,Active,FALSE
Alejandra Bañay,abanay@bitwarden.com,Active,FALSE
Dani Garcia,dgarcia@bitwarden.com,Active,FALSE
Anders Aberg,aaberg@bitwarden.com,Active,FALSE
Andreas Coroiu,acoroiu@bitwarden.com,Active,FALSE
Oscar Hinton,ohinton@bitwarden.com,Active,FALSE
Ope Alao,oalao@bitwarden.com,Active,FALSE
Keith Hubner,khubner@bitwarden.com,Active,FALSE
Matthew Pridgeon,mpridgeon@bitwarden.com,Active,FALSE
Thakshan Sanmugalingam,tsanmugalingam@bitwarden.com,Active,FALSE
Mo Brangier,mbrangier@bitwarden.com,Active,FALSE
Ignacio Fernández,ifernandez@bitwarden.com,Active,FALSE
Fede Monesiglio,fmonesiglio@bitwarden.com,Active,FALSE
Agustín Taruselli,ataruselli@bitwarden.com,Active,FALSE
Alexander Morask,amorask@bitwarden.com,Active,FALSE
Thomas Talty,ttalty@bitwarden.com,Active,FALSE
Audrey Jensen,ajensen@bitwarden.com,Active,FALSE
Ndamati Timothy,ntimothy@bitwarden.com,Active,FALSE
Lotus Mae Scott,lscott@bitwarden.com,Active,FALSE
Robert Y,ry@bitwarden.com,Active,FALSE
Raul Diaz,rdiaz@bitwarden.com,Active,FALSE
Fernando González,fgonzalez@bitwarden.com,Active,FALSE
Addison Beck,adbeck@bitwarden.com,Active,FALSE
Daniel Lufuluabo,dlufuluabo@bitwarden.com,Active,FALSE
Shelby Rinewell,srinewell@bitwarden.com,Active,FALSE
Darilyn Burkman,dburkman@bitwarden.com,Active,FALSE
Patrick Honkonen,phonkonen@bitwarden.com,Active,FALSE
Vicki League,vleague@bitwarden.com,Active,FALSE
Katherine Bertelsen,kbertelsen@bitwarden.com,Active,FALSE
Shelby Palmersheim,spalmersheim@bitwarden.com,Active,FALSE
Andy Murdock,amurdock@bitwarden.com,Active,FALSE
Bernd Schoolmann,bschoolmann@bitwarden.com,Active,FALSE
Maciej Zieniuk,mzieniuk@bitwarden.com,Active,FALSE
Andrew Eyiangho,aeyiangho@bitwarden.com,Active,FALSE
Bob Winchester,bwinchester@bitwarden.com,Active,FALSE
Nadine Bedford,nbedford@bitwarden.com,Active,FALSE
Ramzi Hofayz,rhofayz@bitwarden.com,Active,FALSE
Ned Thompson,nthompson@bitwarden.com,Active,FALSE
Eric Cooley,ecooley@bitwarden.com,Active,FALSE
Rick Charnock,rcharnock@bitwarden.com,Active,FALSE
Wes Salmon,wsalmon@bitwarden.com,Active,FALSE
Peter Way,pway@bitwarden.com,Active,FALSE
Bob Mann-Francis,bmannfrancis@bitwarden.com,Active,FALSE
Paul Schulzetenberg,pschulzetenberg@bitwarden.com,Active,FALSE
Ryan McDowell,rmcdowell@bitwarden.com,Active,FALSE
Adam Eckerle,aeckerle@bitwarden.com,Active,FALSE
Brandon Treston,btreston@bitwarden.com,Active,FALSE
Chris Mackler,cmackler@bitwarden.com,Active,FALSE
Patrick Pimentel,ppimentel@bitwarden.com,Active,FALSE
Andy Pixley,apixley@bitwarden.com,Active,FALSE
Jimmy Vo,jvo@bitwarden.com,Active,FALSE
Jack Bell,jbell@bitwarden.com,Active,FALSE
Amy Galles,agalles@bitwarden.com,Active,FALSE
Matt Andreko,mandreko@bitwarden.com,Active,FALSE
Johanna Gipson,jgipson@bitwarden.com,Active,FALSE
Donald Wilkinson,dwilkinson@bitwarden.com,Active,FALSE
Graham Walker,gwalker@bitwarden.com,Active,FALSE
Vlad Trofimov,vtrofimov@bitwarden.com,Active,FALSE
Daniel Wisotzky,dwisotzky@bitwarden.com,Active,FALSE
Miles Robinson,mrobinson@bitwarden.com,Active,FALSE
Aaron Smith,asmith@bitwarden.com,Active,FALSE
Aaron Mellman,amellman@bitwarden.com,Active,FALSE
Kylar Patrick,kpatrick@bitwarden.com,Active,FALSE
Ashley Dudek,adudek@bitwarden.com,Active,FALSE
Ryan Tuttle,rtuttle@bitwarden.com,Active,FALSE
Mary Blabaum,mblabaum@bitwarden.com,Active,FALSE
Leslie Tilton,ltilton@bitwarden.com,Active,FALSE
Neil Morris,nmorris@bitwarden.com,Active,FALSE
Colm Dalton,cdalton@bitwarden.com,Active,FALSE
Bryan Cunningham,bcunningham@bitwarden.com,Active,FALSE
Brandon Hafler,bhafler@bitwarden.com,Active,FALSE
Noah Peysar,npeysar@bitwarden.com,Active,FALSE
Iris Romero,iromero@bitwarden.com,Active,FALSE
Chelsea Henry,chenry@bitwarden.com,Active,FALSE
Jake Martin,jmartin@bitwarden.com,Active,FALSE
Justin Miller,jmiller@bitwarden.com,Active,FALSE
Ariane Coffin,acoffin@bitwarden.com,Active,FALSE
Barry McSweeney,bmcsweeney@bitwarden.com,Active,FALSE
Lauren Peacock,lpeacock@bitwarden.com,Active,FALSE
Tyler Horrevoets,thorrevoets@bitwarden.com,Active,FALSE
Allison Mahaffey,amahaffey@bitwarden.com,Active,FALSE
Ben Brooks,bbrooks@bitwarden.com,Active,FALSE
Mick Letofsky,mletofsky@bitwarden.com,Active,FALSE
Tammy Schlesinger,tschlesinger@bitwarden.com,Active,FALSE
Tyler Dawes,tdawes@bitwarden.com,Active,FALSE
Dave Brothers,dbrothers@bitwarden.com,Active,FALSE
Nik Gilmore,ngilmore@bitwarden.com,Active,FALSE
Peter Markoe,pmarkoe@bitwarden.com,Active,FALSE
Mark Kincaid,mkincaid@bitwarden.com,Active,FALSE
Renee Lund,rlund@bitwarden.com,Active,FALSE
Nelson Castro,ncastro@bitwarden.com,Active,FALSE
Mehrdad Fathy,mfathy@bitwarden.com,Active,FALSE
Derek Nance,dnance@bitwarden.com,Active,FALSE
Alex Dewitt,adewitt@bitwarden.com,Active,FALSE
Capen Apple,capple@bitwarden.com,Active,FALSE
Tyler Hirst,thirst@bitwarden.com,Active,FALSE
Kyle Denney,kdenney@bitwarden.com,Active,FALSE
Kate Settle,ksettle@bitwarden.com,Active,FALSE
Christian Tolman,ctolman@bitwarden.com,Active,FALSE
Kyle Criddle,kcriddle@bitwarden.com,Active,FALSE
Missy Katner,mkatner@bitwarden.com,Active,FALSE
John Harrington,jharrington@bitwarden.com,Active,FALSE
Emily Bischoff,ebischoff@bitwarden.com,Active,FALSE
Isaiah Inuwa,iinuwa@bitwarden.com,Active,FALSE
Samantha Peña,spena@bitwarden.com,Active,FALSE
David Galda,dgalda@bitwarden.com,Active,FALSE
Adam Martinez,amartinez@bitwarden.com,Active,FALSE
Patrick Kiel,pkiel@bitwarden.com,Active,FALSE
Marley Zendejas,mzendejas@bitwarden.com,Active,FALSE
Mike Amirault,mamirault@bitwarden.com,Active,FALSE
Lou Canton,lcanton@bitwarden.com,Active,FALSE
Brian Simms,bsimms@bitwarden.com,Active,FALSE
Noah Bowman,nbowman@bitwarden.com,Active,FALSE
Brandon Biete,bbiete@bitwarden.com,Active,FALSE
Eli Grubb,egrubb@bitwarden.com,Active,FALSE
Alex Dragovich,adragovich@bitwarden.com,Active,FALSE
Michelle Silva,msilva@bitwarden.com,Active,FALSE
Benjamin McFerren,bmcferren@bitwarden.com,Active,FALSE
Dan Morriss,dmorriss@bitwarden.com,Active,FALSE
Allie Watkins,awatkins@bitwarden.com,Active,FALSE
Sven Vernyi,svernyi@bitwarden.com,Active,FALSE
Jackson Engstrom,jengstrom@bitwarden.com,Active,FALSE
Daniel Soria-Galvarro,dsoriagalvarro@bitwarden.com,Active,FALSE
Isabella Iannitti,iiannitti@bitwarden.com,Active,FALSE
Kevin Mancusi,kmancusi@bitwarden.com,Active,FALSE
Demetri Efthymiou,defthymiou@bitwarden.com,Active,FALSE
Jared Scarito,jscarito@bitwarden.com,Active,FALSE
Alastair Spencer,aspencer@bitwarden.com,Active,FALSE
Jillian Chueka,jchueka@bitwarden.com,Active,FALSE
Brad Deibert,bdeibert@bitwarden.com,Active,FALSE
Chloe McLaughlin,cmclaughlin@bitwarden.com,Active,FALSE
Kyleigh Bonner,kbonner@bitwarden.com,Active,FALSE
Rishika Sokke Geethachari,rgeethachari@bitwarden.com,Active,FALSE
Mike Sullivan,msullivan@bitwarden.com,Active,FALSE
Marc Schillig,mschillig@bitwarden.com,Active,FALSE
Ayane Materia,amateria@bitwarden.com,Active,FALSE
Derek Fisher,dfisher@bitwarden.com,Active,FALSE
Emily Ivy,eivy@bitwarden.com,Active,FALSE
Morgan Zellers,mzellers@bitwarden.com,Active,FALSE
Corbet Weller,cweller@bitwarden.com,Active,FALSE
Jason Miller,jamiller@bitwarden.com,Active,FALSE
David Redmond,dredmond@bitwarden.com,Active,FALSE
Elizabeth Schierloh,eschierloh@bitwarden.com,Active,FALSE
Alex Roberts,aroberts@bitwarden.com,Active,FALSE
Ana Horsch,ahorsch@bitwarden.com,Active,FALSE
Nidhi Teerdhala,nteerdhala@bitwarden.com,Active,FALSE
Jeannine Stadnyk,jstadnyk@bitwarden.com,Active,FALSE
Alex Brown,abrown@bitwarden.com,Active,FALSE
Jonathon Cartwright,jcartwright@bitwarden.com,Active,FALSE
Amo Adams,aadams@bitwarden.com,Active,FALSE
Gino G,gg@bitwarden.com,Active,FALSE
Debra Daniel-Aleonomoh,ddanielaleonomoh@bitwarden.com,Active,FALSE
Michael Shenkman,mshenkman@bitwarden.com,Active,FALSE
Andrew Wiester,awiester@bitwarden.com,Active,FALSE
Chad Tatum,ctatum@bitwarden.com,Active,FALSE
Chris Wixted,cwixted@bitwarden.com,Active,FALSE
Anvita Kapila,akapila@bitwarden.com,Active,FALSE
Patrik Svensson,psvensson@bitwarden.com,Active,FALSE
Alex Colom,acolom@bitwarden.com,Active,FALSE
James Johnson,jjohnson@bitwarden.com,Active,FALSE
Alex Jorge,ajorge@bitwarden.com,Active,FALSE
Andrew Park,apark@bitwarden.com,Active,FALSE
Josue Brucelas,jbrucelas@bitwarden.com,Active,FALSE
Mat Sinclair,msinclair@bitwarden.com,Active,FALSE
Jennifer Wilson,jwilson@bitwarden.com,Active,FALSE
Andrew Hartnett,ahartnett@bitwarden.com,Active,FALSE
Eric Sognefest,esognefest@bitwarden.com,Active,FALSE
Shauna Coleman,scoleman@bitwarden.com,Active,FALSE
Antonis Bekiris,abekiris@bitwarden.com,Active,FALSE
Rainya Mosher,rmosher@bitwarden.com,Active,FALSE
Kevin Driscoll,kdriscoll@bitwarden.com,Active,FALSE
Mark Quitevis,mquitevis@bitwarden.com,Active,FALSE
Sushmita Das,sdas@bitwarden.com,Active,FALSE
Kristi Moore,kmoore@bitwarden.com,Active,FALSE
Meenakshi Kogje,mkogje@bitwarden.com,Active,FALSE
Paolo Bernewitz,pbernewitz@bitwarden.com,Active,FALSE
Andrew Phillips,aphillips@bitwarden.com,Active,FALSE
Prafful Nagwani,pnagwani@bitwarden.com,Active,FALSE
Ryan Fecher,rfecher@bitwarden.com,Active,FALSE
Mark Wilson,mwilson@bitwarden.com,Active,FALSE
Jack McLaughlin,jmclaughlin@bitwarden.com,Active,FALSE
Toby Thorslund,tthorslund@bitwarden.com,Active,FALSE
Madeline Delaney,mdelaney@bitwarden.com,Active,FALSE
Alan Guzman,aguzman@bitwarden.com,Active,FALSE
David Combs,dcombs@bitwarden.com,Active,FALSE
Mary Writz,mwritz@bitwarden.com,Active,FALSE
Mukul Pal,mpal@bitwarden.com,Active,FALSE
Rohan Suneja,rsuneja@bitwarden.com,Active,FALSE
Dominic Paszkiewicz,dpaszkiewicz@bitwarden.com,Active,FALSE
`;
